### ISSUE TITLE
Unable to compile dayz.pwn

### ISSUE THREAD

**Issue by Rattle189** [AaronNader96/Project-DayZ-SAMP#3]
`D:\Toolbox\SA-MP DAYZ Server\pawno\include\YSI\internal\..\y_va.inc(100) : fatal error 100: cannot read from file: "y_va/impl"

Compilation aborted.Pawn compiler 3.2.3664	 	 	Copyright (c) 1997-2006, ITB CompuPhase

1 Error.
`
This error is generated every time I attempt to compile the gamemode. I have extracted the SA-MP server package first, then merged the SA-MP DAYZ package inside afterwards.

**Comment by Rattle189** [comment]
Bump

**Comment by Rattle189** [comment]
Bump

**Comment by AaronNader96** [comment]
You need to download y_va packages via https://github.com/pawn-lang/YSI-Includes/releases

**Comment by AmirTuxer** [comment]
Doesn't the video have an tutorial?

**Comment by Leonardoshz** [comment]
How to create the sql database

**Comment by AaronNader96** [comment]
Its under public OnGameModeInit()

**Comment by Riot20** [comment]
I tried all YSI versions, several of them worked. But the compiled file are empty (dayz.amx).
Hence when I tried to start the server during Filterscripts this error appeared and the server failed to start.

Filterscripts
---------------
  Loaded 0 filterscripts.

Script[gamemodes/dayz.amx]: Run time error 17: "Invalid/unsupported P-code file format"
Failed to load 'gamemodes/dayz.amx' script.
Number of vehicle models: 0

______________________________________________________________________
Could you just update it and include all required YSI files instead?
